proxy:
  secretToken: 
  https:
    enabled: true
    hosts:
      - jupyter.fabric-testbed.net
    type: manual
    manual:
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        -----END RSA PRIVATE KEY-----
      cert: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
singleuser:
  cpu:
    limit: 4
    guarantee: 0.05
  memory:
    limit: 2G
    guarantee: 512M
  image: 
    name: fabrictestbed/jupyter-notebook
    tag: 1.5.0
  extraEnv:
    FABRIC_CREDMGR_HOST: cm.fabric-testbed.net
    FABRIC_ORCHESTRATOR_HOST: orchestrator.fabric-testbed.net
    FABRIC_TOKEN_LOCATION: /home/fabric/.tokens.json
    FABRIC_NOTEBOOK_LOCATION: /home/fabric/work
    FABRIC_NOTEBOOK_TAGS: rel1.5.0
    FABRIC_NOTEBOOK_REPO_URL: https://github.com/fabric-testbed/jupyter-examples/archive/refs/tags/
    FABRIC_CONFIG_LOCATION: /home/fabric/work/fabric_config
    FABRIC_BASTION_HOST: bastion.fabric-testbed.net
    FABRIC_BASTION_PRIVATE_KEY_NAME: fabric-bastion-key
    FABRIC_SLICE_PRIVATE_KEY_NAME: slice_key
    FABRIC_SLICE_PUBLIC_KEY_NAME: slice_key.pub
  defaultUrl: "/lab"
  storage:
    capacity: 1Gi
    homeMountPath: /home/fabric/work
  lifecycleHooks:
    postStart:
      exec:
          command: ["/opt/conda/bin/python3.9", "/opt/conda/lib/python3.9/site-packages/jupyternb/jupyter_startup.py"]
  profileList:
    - display_name: "FABRIC Examples v1.4.6,  FABlib v1.4.4: released: 05/21/2023, stable: Summer 2023"
      kubespawner_override:
        image: fabrictestbed/jupyter-notebook:1.4.4
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - |
                  export FABRIC_NOTEBOOK_TAGS=rel1.4.6
                  /opt/conda/bin/python3.9 /opt/conda/lib/python3.9/site-packages/jupyternb/jupyter_startup.py
    - display_name: "(default) FABRIC Examples v1.5.0,  FABlib v1.5.0: released: 06/12/2023, stable: Fall 2023"
      default: true
    - display_name: "(bleeding edge) FABRIC Examples latest, FABlib latest, Current Release"
      kubespawner_override:
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - |
                  export FABRIC_NOTEBOOK_TAGS=curl -s https://api.github.com/repos/fabric-testbed/jupyter-examples/releases/latest | grep '"tag_name":' | cut -d '"' -f 4
                  /opt/conda/bin/python3.9 /opt/conda/lib/python3.9/site-packages/jupyternb/jupyter_startup.py
                  /opt/conda/bin/pip install --ignore-installed fabrictestbed-extensions
    - display_name: "(beyond bleeding edge) FABRIC Examples (main branch), FABlib (master branch)"
      kubespawner_override:
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - |
                  /opt/conda/bin/python3.9 /opt/conda/lib/python3.9/site-packages/jupyternb/jupyter_startup.py
                  /opt/conda/bin/pip install -e git+https://github.com/fabric-testbed/fabrictestbed-extensions@main
                  git clone https://github.com/fabric-testbed/fabrictestbed-extensions.git /home/fabric/fabrictestbed-extensions
                  if [ ! -d "/home/fabric/work/jupyter-examples" ]; then
                    git clone https://github.com/fabric-testbed/jupyter-examples.git /home/fabric/work/jupyter-examples
                  fi
hub:
  image: 
    name: fabrictestbed/jupyterhub-k8s
    tag: 1.4.0
  config:
    Authenticator:
      admin_users:
        - kthare10@email.unc.edu
        - stealey@email.unc.edu
      enable_auth_state: True
      refresh_pre_spawn: True 
      auth_refresh_age: 86400
    JupyterHub:
      authenticator_class: fabricauthenticator.fabricauthenticator.FabricAuthenticator
      cookie_secret: 
    CILogonOAuthenticator:
      username_claim: email
      client_id: 
      client_secret: 
      oauth_callback_url: https://jupyter.fabric-testbed.net/hub/oauth_callback
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
      c.KubeSpawner.extra_pod_config = {
         "restartPolicy": "OnFailure"
      }
  extraEnv:
    # see https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#authentication-state
    # for JUPYTERHUB_CRYPT_KEY
    JUPYTERHUB_CRYPT_KEY: 
    # the FABRIC CILogon instance LDAP setting:
    LDAP_HOST: 
    LDAP_USER: 
    LDAP_PASSWORD: 
    LDAP_SEARCH_BASE: 
    FABRIC_COU_JUPYTERHUB: CO:COU:Jupyterhub:members:active
cull:
  timeout: 3600   # 1 hr
  every: 600      # check performs every 10 mins
  maxAge: 86400  # 24 hrs

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 3
  userPods:
    nodeAffinity:
      matchNodePurpose: require
