FROM jupyterhub/jupyterhub:1.2
COPY requirements.txt /srv/jupyterhub/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /srv/jupyterhub/requirements.txt
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
COPY cull_idle_servers.py /srv/jupyterhub/cull_idle_servers.py
COPY adminlist /srv/jupyterhub/adminlist
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
